# Generated by Django 5.1.3 on 2024-11-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250),
            preserve_default=False,
        ),
    ]
